# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legaltext', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaltext',
            name='slug',
            field=models.SlugField(max_length=64, unique=True, verbose_name='Slug'),
        ),
    ]
