# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legaltext', '0002_legaltextcheckbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaltext',
            name='url_name',
            field=models.SlugField(blank=True, help_text='Optional URL name for the legal text. If not provided, the slug is used.', max_length=64, null=True, unique=True, verbose_name='URL Name'),
        ),
    ]
