# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-13 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legaltext', '0003_legaltext_url_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legaltextcheckbox',
            options={'ordering': ('legaltext_version', 'order'), 'verbose_name': 'Legal text checkbox', 'verbose_name_plural': 'Legal text Checkboxes'},
        ),
        migrations.AddField(
            model_name='legaltextcheckbox',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Order'),
        ),
        migrations.AlterUniqueTogether(
            name='legaltextcheckbox',
            unique_together=set([('legaltext_version', 'order')]),
        ),
    ]
