# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-22 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legaltext', '0004_auto_20170913_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaltext',
            name='slug',
            field=models.SlugField(max_length=128, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='legaltext',
            name='url_name',
            field=models.SlugField(blank=True, help_text='Optional URL name for the legal text. If not provided, the slug is used.', max_length=128, null=True, unique=True, verbose_name='URL Name'),
        ),
    ]
