sudo: false
language: python

python:
  - '3.5'

env:
  - DJANGO_VERSION=1.10.x
  - DJANGO_VERSION=1.9.x

install:
  - pip install tox

script:
  - tox -e "$TRAVIS_PYTHON_VERSION-$DJANGO_VERSION"

after_success:
  - pip install coveralls coverage
  - coverage report
  - coveralls

notifications:
  slack:
    secure: