# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import legaltext.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legaltext', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_submit', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_privacy', legaltext.fields.LegalTextField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', slug=None, to='legaltext.LegalTextVersion')),
                ('accepted_terms', legaltext.fields.LegalTextField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', slug=None, to='legaltext.LegalTextVersion')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('privacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='legaltext.LegalText')),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='legaltext.LegalText')),
            ],
        ),
    ]
