# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import legaltext.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legaltext', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockSurveyParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('date_submit', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Survey submited date')),
                ('accepted_privacy', legaltext.fields.LegalTextField(blank=True, default=legaltext.fields.CurrentLegalText('mockapp-privacy'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', slug='mockapp-privacy', to='legaltext.LegalTextVersion')),
                ('accepted_terms', legaltext.fields.LegalTextField(blank=True, default=legaltext.fields.CurrentLegalText('mockapp-terms'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', slug='mockapp-terms', to='legaltext.LegalTextVersion')),
            ],
        ),
    ]
